# TCL File Generated by Component Editor 16.0
# Tue Oct 17 10:14:53 BST 2017
# DO NOT MODIFY


# 
# ASIC_avalon "ASIC_avalon" v1.0
#  2017.10.17.10:14:53
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module ASIC_avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME ASIC_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ASIC_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ASIC_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ASIC_avalon.sv SYSTEM_VERILOG PATH ../source/ASIC_avalon.sv TOP_LEVEL_FILE
add_fileset_file ASIC.sv SYSTEM_VERILOG PATH ../source/ASIC.sv
add_fileset_file Alpha.sv SYSTEM_VERILOG PATH ../source/Alpha.sv
add_fileset_file Alpha_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Alpha_Pipe_razor1.sv
add_fileset_file Alpha_razor1.sv SYSTEM_VERILOG PATH ../source/Alpha_razor1.sv
add_fileset_file Beta.sv SYSTEM_VERILOG PATH ../source/Beta.sv
add_fileset_file Beta_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Beta_Pipe_razor1.sv
add_fileset_file Beta_razor1.sv SYSTEM_VERILOG PATH ../source/Beta_razor1.sv
add_fileset_file BitClip.sv SYSTEM_VERILOG PATH ../source/BitClip.sv
add_fileset_file Control.sv SYSTEM_VERILOG PATH ../source/Control.sv
add_fileset_file DMUXS.sv SYSTEM_VERILOG PATH ../source/DMUXS.sv
add_fileset_file Epsilon_Pipe.sv SYSTEM_VERILOG PATH ../source/Epsilon_Pipe.sv
add_fileset_file Epsilon_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Epsilon_Pipe_razor1.sv
add_fileset_file ErrorReg.sv SYSTEM_VERILOG PATH ../source/ErrorReg.sv
add_fileset_file Error_Counter.sv SYSTEM_VERILOG PATH ../source/Error_Counter.sv
add_fileset_file Error_Section.sv SYSTEM_VERILOG PATH ../source/Error_Section.sv
add_fileset_file Error_Section_Pipe.sv SYSTEM_VERILOG PATH ../source/Error_Section_Pipe.sv
add_fileset_file EstimatedBit.sv SYSTEM_VERILOG PATH ../source/EstimatedBit.sv
add_fileset_file Ext.sv SYSTEM_VERILOG PATH ../source/Ext.sv
add_fileset_file Ext_Pipe.sv SYSTEM_VERILOG PATH ../source/Ext_Pipe.sv
add_fileset_file Ext_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Ext_Pipe_razor1.sv
add_fileset_file Ext_razor1.sv SYSTEM_VERILOG PATH ../source/Ext_razor1.sv
add_fileset_file FPTD.sv SYSTEM_VERILOG PATH ../source/FPTD.sv
add_fileset_file FPTD_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/FPTD_Pipe_razor1.sv
add_fileset_file Gamma.sv SYSTEM_VERILOG PATH ../source/Gamma.sv
add_fileset_file Gamma_Pipe.sv SYSTEM_VERILOG PATH ../source/Gamma_Pipe.sv
add_fileset_file Gamma_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Gamma_Pipe_razor1.sv
add_fileset_file Gamma_Termination.sv SYSTEM_VERILOG PATH ../source/Gamma_Termination.sv
add_fileset_file InShiftReg.sv SYSTEM_VERILOG PATH ../source/InShiftReg.sv
add_fileset_file LowerDecoder.sv SYSTEM_VERILOG PATH ../source/LowerDecoder.sv
add_fileset_file LowerDecoder_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/LowerDecoder_Pipe_razor1.sv
add_fileset_file MUXS.sv SYSTEM_VERILOG PATH ../source/MUXS.sv
add_fileset_file OutShiftReg.sv SYSTEM_VERILOG PATH ../source/OutShiftReg.sv
add_fileset_file Section.sv SYSTEM_VERILOG PATH ../source/Section.sv
add_fileset_file Section_NoAlpha.sv SYSTEM_VERILOG PATH ../source/Section_NoAlpha.sv
add_fileset_file Section_NoAlpha_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Section_NoAlpha_Pipe_razor1.sv
add_fileset_file Section_NoBeta.sv SYSTEM_VERILOG PATH ../source/Section_NoBeta.sv
add_fileset_file Section_NoBeta_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Section_NoBeta_Pipe_razor1.sv
add_fileset_file Section_Pipe.sv SYSTEM_VERILOG PATH ../source/Section_Pipe.sv
add_fileset_file Section_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Section_Pipe_razor1.sv
add_fileset_file Section_Termination.sv SYSTEM_VERILOG PATH ../source/Section_Termination.sv
add_fileset_file Section_razor1.sv SYSTEM_VERILOG PATH ../source/Section_razor1.sv
add_fileset_file SysControl.sv SYSTEM_VERILOG PATH ../source/SysControl.sv
add_fileset_file Tmodel.sv SYSTEM_VERILOG PATH ../source/Tmodel.sv
add_fileset_file UpperDecoder.sv SYSTEM_VERILOG PATH ../source/UpperDecoder.sv
add_fileset_file UpperDecoder_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/UpperDecoder_Pipe_razor1.sv
add_fileset_file divider.sv SYSTEM_VERILOG PATH ../source/divider.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ASIC_avalon
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file ASIC_avalon.sv SYSTEM_VERILOG PATH ../source/ASIC_avalon.sv
add_fileset_file ASIC.sv SYSTEM_VERILOG PATH ../source/ASIC.sv
add_fileset_file Alpha.sv SYSTEM_VERILOG PATH ../source/Alpha.sv
add_fileset_file Alpha_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Alpha_Pipe_razor1.sv
add_fileset_file Alpha_razor1.sv SYSTEM_VERILOG PATH ../source/Alpha_razor1.sv
add_fileset_file Beta.sv SYSTEM_VERILOG PATH ../source/Beta.sv
add_fileset_file Beta_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Beta_Pipe_razor1.sv
add_fileset_file Beta_razor1.sv SYSTEM_VERILOG PATH ../source/Beta_razor1.sv
add_fileset_file BitClip.sv SYSTEM_VERILOG PATH ../source/BitClip.sv
add_fileset_file Control.sv SYSTEM_VERILOG PATH ../source/Control.sv
add_fileset_file DMUXS.sv SYSTEM_VERILOG PATH ../source/DMUXS.sv
add_fileset_file Epsilon_Pipe.sv SYSTEM_VERILOG PATH ../source/Epsilon_Pipe.sv
add_fileset_file Epsilon_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Epsilon_Pipe_razor1.sv
add_fileset_file ErrorReg.sv SYSTEM_VERILOG PATH ../source/ErrorReg.sv
add_fileset_file Error_Counter.sv SYSTEM_VERILOG PATH ../source/Error_Counter.sv
add_fileset_file Error_Section.sv SYSTEM_VERILOG PATH ../source/Error_Section.sv
add_fileset_file Error_Section_Pipe.sv SYSTEM_VERILOG PATH ../source/Error_Section_Pipe.sv
add_fileset_file EstimatedBit.sv SYSTEM_VERILOG PATH ../source/EstimatedBit.sv
add_fileset_file Ext.sv SYSTEM_VERILOG PATH ../source/Ext.sv
add_fileset_file Ext_Pipe.sv SYSTEM_VERILOG PATH ../source/Ext_Pipe.sv
add_fileset_file Ext_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Ext_Pipe_razor1.sv
add_fileset_file Ext_razor1.sv SYSTEM_VERILOG PATH ../source/Ext_razor1.sv
add_fileset_file FPTD.sv SYSTEM_VERILOG PATH ../source/FPTD.sv
add_fileset_file FPTD_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/FPTD_Pipe_razor1.sv
add_fileset_file Gamma.sv SYSTEM_VERILOG PATH ../source/Gamma.sv
add_fileset_file Gamma_Pipe.sv SYSTEM_VERILOG PATH ../source/Gamma_Pipe.sv
add_fileset_file Gamma_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Gamma_Pipe_razor1.sv
add_fileset_file Gamma_Termination.sv SYSTEM_VERILOG PATH ../source/Gamma_Termination.sv
add_fileset_file InShiftReg.sv SYSTEM_VERILOG PATH ../source/InShiftReg.sv
add_fileset_file LowerDecoder.sv SYSTEM_VERILOG PATH ../source/LowerDecoder.sv
add_fileset_file LowerDecoder_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/LowerDecoder_Pipe_razor1.sv
add_fileset_file MUXS.sv SYSTEM_VERILOG PATH ../source/MUXS.sv
add_fileset_file OutShiftReg.sv SYSTEM_VERILOG PATH ../source/OutShiftReg.sv
add_fileset_file Section.sv SYSTEM_VERILOG PATH ../source/Section.sv
add_fileset_file Section_NoAlpha.sv SYSTEM_VERILOG PATH ../source/Section_NoAlpha.sv
add_fileset_file Section_NoAlpha_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Section_NoAlpha_Pipe_razor1.sv
add_fileset_file Section_NoBeta.sv SYSTEM_VERILOG PATH ../source/Section_NoBeta.sv
add_fileset_file Section_NoBeta_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Section_NoBeta_Pipe_razor1.sv
add_fileset_file Section_Pipe.sv SYSTEM_VERILOG PATH ../source/Section_Pipe.sv
add_fileset_file Section_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/Section_Pipe_razor1.sv
add_fileset_file Section_Termination.sv SYSTEM_VERILOG PATH ../source/Section_Termination.sv
add_fileset_file Section_razor1.sv SYSTEM_VERILOG PATH ../source/Section_razor1.sv
add_fileset_file SysControl.sv SYSTEM_VERILOG PATH ../source/SysControl.sv
add_fileset_file Tmodel.sv SYSTEM_VERILOG PATH ../source/Tmodel.sv
add_fileset_file UpperDecoder.sv SYSTEM_VERILOG PATH ../source/UpperDecoder.sv
add_fileset_file UpperDecoder_Pipe_razor1.sv SYSTEM_VERILOG PATH ../source/UpperDecoder_Pipe_razor1.sv
add_fileset_file divider.sv SYSTEM_VERILOG PATH ../source/divider.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset resetn reset_n Input 1


# 
# connection point sink
# 
add_interface sink avalon_streaming end
set_interface_property sink associatedClock clock
set_interface_property sink associatedReset reset
set_interface_property sink dataBitsPerSymbol 8
set_interface_property sink errorDescriptor ""
set_interface_property sink firstSymbolInHighOrderBits true
set_interface_property sink maxChannel 0
set_interface_property sink readyLatency 0
set_interface_property sink ENABLED true
set_interface_property sink EXPORT_OF ""
set_interface_property sink PORT_NAME_MAP ""
set_interface_property sink CMSIS_SVD_VARIABLES ""
set_interface_property sink SVD_ADDRESS_GROUP ""

add_interface_port sink sink_data data Input 32
add_interface_port sink sink_eop endofpacket Input 1
add_interface_port sink sink_ready ready Output 1
add_interface_port sink sink_sop startofpacket Input 1
add_interface_port sink sink_valid valid Input 1


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clock
set_interface_property source associatedReset reset
set_interface_property source dataBitsPerSymbol 8
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 0
set_interface_property source ENABLED true
set_interface_property source EXPORT_OF ""
set_interface_property source PORT_NAME_MAP ""
set_interface_property source CMSIS_SVD_VARIABLES ""
set_interface_property source SVD_ADDRESS_GROUP ""

add_interface_port source source_data data Output 32
add_interface_port source source_eop endofpacket Output 1
add_interface_port source source_ready ready Input 1
add_interface_port source source_sop startofpacket Output 1
add_interface_port source source_valid valid Output 1


# 
# connection point asic_dout1
# 
add_interface asic_dout1 avalon_streaming end
set_interface_property asic_dout1 associatedClock clock
set_interface_property asic_dout1 associatedReset reset
set_interface_property asic_dout1 dataBitsPerSymbol 1
set_interface_property asic_dout1 errorDescriptor ""
set_interface_property asic_dout1 firstSymbolInHighOrderBits true
set_interface_property asic_dout1 maxChannel 0
set_interface_property asic_dout1 readyLatency 0
set_interface_property asic_dout1 ENABLED true
set_interface_property asic_dout1 EXPORT_OF ""
set_interface_property asic_dout1 PORT_NAME_MAP ""
set_interface_property asic_dout1 CMSIS_SVD_VARIABLES ""
set_interface_property asic_dout1 SVD_ADDRESS_GROUP ""

add_interface_port asic_dout1 ASIC_DOut1 data Input 7


# 
# connection point asic_dout2
# 
add_interface asic_dout2 avalon_streaming end
set_interface_property asic_dout2 associatedClock clock
set_interface_property asic_dout2 associatedReset reset
set_interface_property asic_dout2 dataBitsPerSymbol 1
set_interface_property asic_dout2 errorDescriptor ""
set_interface_property asic_dout2 firstSymbolInHighOrderBits true
set_interface_property asic_dout2 maxChannel 0
set_interface_property asic_dout2 readyLatency 0
set_interface_property asic_dout2 ENABLED true
set_interface_property asic_dout2 EXPORT_OF ""
set_interface_property asic_dout2 PORT_NAME_MAP ""
set_interface_property asic_dout2 CMSIS_SVD_VARIABLES ""
set_interface_property asic_dout2 SVD_ADDRESS_GROUP ""

add_interface_port asic_dout2 ASIC_DOut2 data Input 7


# 
# connection point asic_dclk
# 
add_interface asic_dclk avalon_streaming end
set_interface_property asic_dclk associatedClock clock
set_interface_property asic_dclk associatedReset reset
set_interface_property asic_dclk dataBitsPerSymbol 1
set_interface_property asic_dclk errorDescriptor ""
set_interface_property asic_dclk firstSymbolInHighOrderBits true
set_interface_property asic_dclk maxChannel 0
set_interface_property asic_dclk readyLatency 0
set_interface_property asic_dclk ENABLED true
set_interface_property asic_dclk EXPORT_OF ""
set_interface_property asic_dclk PORT_NAME_MAP ""
set_interface_property asic_dclk CMSIS_SVD_VARIABLES ""
set_interface_property asic_dclk SVD_ADDRESS_GROUP ""

add_interface_port asic_dclk ASIC_Dclk data Input 1


# 
# connection point asic_keepshift
# 
add_interface asic_keepshift avalon_streaming end
set_interface_property asic_keepshift associatedClock clock
set_interface_property asic_keepshift associatedReset reset
set_interface_property asic_keepshift dataBitsPerSymbol 1
set_interface_property asic_keepshift errorDescriptor ""
set_interface_property asic_keepshift firstSymbolInHighOrderBits true
set_interface_property asic_keepshift maxChannel 0
set_interface_property asic_keepshift readyLatency 0
set_interface_property asic_keepshift ENABLED true
set_interface_property asic_keepshift EXPORT_OF ""
set_interface_property asic_keepshift PORT_NAME_MAP ""
set_interface_property asic_keepshift CMSIS_SVD_VARIABLES ""
set_interface_property asic_keepshift SVD_ADDRESS_GROUP ""

add_interface_port asic_keepshift ASIC_KeepShift data Input 1


# 
# connection point asic_start
# 
add_interface asic_start avalon_streaming end
set_interface_property asic_start associatedClock clock
set_interface_property asic_start associatedReset reset
set_interface_property asic_start dataBitsPerSymbol 1
set_interface_property asic_start errorDescriptor ""
set_interface_property asic_start firstSymbolInHighOrderBits true
set_interface_property asic_start maxChannel 0
set_interface_property asic_start readyLatency 0
set_interface_property asic_start ENABLED true
set_interface_property asic_start EXPORT_OF ""
set_interface_property asic_start PORT_NAME_MAP ""
set_interface_property asic_start CMSIS_SVD_VARIABLES ""
set_interface_property asic_start SVD_ADDRESS_GROUP ""

add_interface_port asic_start ASIC_Start data Input 1


# 
# connection point asic_start2
# 
add_interface asic_start2 avalon_streaming end
set_interface_property asic_start2 associatedClock clock
set_interface_property asic_start2 associatedReset reset
set_interface_property asic_start2 dataBitsPerSymbol 1
set_interface_property asic_start2 errorDescriptor ""
set_interface_property asic_start2 firstSymbolInHighOrderBits true
set_interface_property asic_start2 maxChannel 0
set_interface_property asic_start2 readyLatency 0
set_interface_property asic_start2 ENABLED true
set_interface_property asic_start2 EXPORT_OF ""
set_interface_property asic_start2 PORT_NAME_MAP ""
set_interface_property asic_start2 CMSIS_SVD_VARIABLES ""
set_interface_property asic_start2 SVD_ADDRESS_GROUP ""

add_interface_port asic_start2 ASIC_Start2 data Input 1


# 
# connection point asic_tout
# 
add_interface asic_tout avalon_streaming end
set_interface_property asic_tout associatedClock clock
set_interface_property asic_tout associatedReset reset
set_interface_property asic_tout dataBitsPerSymbol 1
set_interface_property asic_tout errorDescriptor ""
set_interface_property asic_tout firstSymbolInHighOrderBits true
set_interface_property asic_tout maxChannel 0
set_interface_property asic_tout readyLatency 0
set_interface_property asic_tout ENABLED true
set_interface_property asic_tout EXPORT_OF ""
set_interface_property asic_tout PORT_NAME_MAP ""
set_interface_property asic_tout CMSIS_SVD_VARIABLES ""
set_interface_property asic_tout SVD_ADDRESS_GROUP ""

add_interface_port asic_tout ASIC_TOut data Input 7


# 
# connection point asic_testready
# 
add_interface asic_testready avalon_streaming end
set_interface_property asic_testready associatedClock clock
set_interface_property asic_testready associatedReset reset
set_interface_property asic_testready dataBitsPerSymbol 1
set_interface_property asic_testready errorDescriptor ""
set_interface_property asic_testready firstSymbolInHighOrderBits true
set_interface_property asic_testready maxChannel 0
set_interface_property asic_testready readyLatency 0
set_interface_property asic_testready ENABLED true
set_interface_property asic_testready EXPORT_OF ""
set_interface_property asic_testready PORT_NAME_MAP ""
set_interface_property asic_testready CMSIS_SVD_VARIABLES ""
set_interface_property asic_testready SVD_ADDRESS_GROUP ""

add_interface_port asic_testready ASIC_TestReady data Input 1


# 
# connection point asic_bitout1
# 
add_interface asic_bitout1 avalon_streaming end
set_interface_property asic_bitout1 associatedClock clock
set_interface_property asic_bitout1 associatedReset reset
set_interface_property asic_bitout1 dataBitsPerSymbol 1
set_interface_property asic_bitout1 errorDescriptor ""
set_interface_property asic_bitout1 firstSymbolInHighOrderBits true
set_interface_property asic_bitout1 maxChannel 0
set_interface_property asic_bitout1 readyLatency 0
set_interface_property asic_bitout1 ENABLED true
set_interface_property asic_bitout1 EXPORT_OF ""
set_interface_property asic_bitout1 PORT_NAME_MAP ""
set_interface_property asic_bitout1 CMSIS_SVD_VARIABLES ""
set_interface_property asic_bitout1 SVD_ADDRESS_GROUP ""

add_interface_port asic_bitout1 ASIC_bitout1 data Input 1


# 
# connection point asic_bitout2
# 
add_interface asic_bitout2 avalon_streaming end
set_interface_property asic_bitout2 associatedClock clock
set_interface_property asic_bitout2 associatedReset reset
set_interface_property asic_bitout2 dataBitsPerSymbol 1
set_interface_property asic_bitout2 errorDescriptor ""
set_interface_property asic_bitout2 firstSymbolInHighOrderBits true
set_interface_property asic_bitout2 maxChannel 0
set_interface_property asic_bitout2 readyLatency 0
set_interface_property asic_bitout2 ENABLED true
set_interface_property asic_bitout2 EXPORT_OF ""
set_interface_property asic_bitout2 PORT_NAME_MAP ""
set_interface_property asic_bitout2 CMSIS_SVD_VARIABLES ""
set_interface_property asic_bitout2 SVD_ADDRESS_GROUP ""

add_interface_port asic_bitout2 ASIC_bitout2 data Input 1


# 
# connection point asic_switch_fpga_asic
# 
add_interface asic_switch_fpga_asic avalon_streaming end
set_interface_property asic_switch_fpga_asic associatedClock clock
set_interface_property asic_switch_fpga_asic associatedReset reset
set_interface_property asic_switch_fpga_asic dataBitsPerSymbol 1
set_interface_property asic_switch_fpga_asic errorDescriptor ""
set_interface_property asic_switch_fpga_asic firstSymbolInHighOrderBits true
set_interface_property asic_switch_fpga_asic maxChannel 0
set_interface_property asic_switch_fpga_asic readyLatency 0
set_interface_property asic_switch_fpga_asic ENABLED true
set_interface_property asic_switch_fpga_asic EXPORT_OF ""
set_interface_property asic_switch_fpga_asic PORT_NAME_MAP ""
set_interface_property asic_switch_fpga_asic CMSIS_SVD_VARIABLES ""
set_interface_property asic_switch_fpga_asic SVD_ADDRESS_GROUP ""

add_interface_port asic_switch_fpga_asic switch_fpga_asic data Input 1


# 
# connection point asic_clock
# 
add_interface asic_clock clock start
set_interface_property asic_clock associatedDirectClock ""
set_interface_property asic_clock clockRate 0
set_interface_property asic_clock clockRateKnown false
set_interface_property asic_clock ENABLED true
set_interface_property asic_clock EXPORT_OF ""
set_interface_property asic_clock PORT_NAME_MAP ""
set_interface_property asic_clock CMSIS_SVD_VARIABLES ""
set_interface_property asic_clock SVD_ADDRESS_GROUP ""

add_interface_port asic_clock ASIC_Clock clk Output 1


# 
# connection point asic_nreset
# 
add_interface asic_nreset avalon_streaming start
set_interface_property asic_nreset associatedClock clock
set_interface_property asic_nreset associatedReset reset
set_interface_property asic_nreset dataBitsPerSymbol 1
set_interface_property asic_nreset errorDescriptor ""
set_interface_property asic_nreset firstSymbolInHighOrderBits true
set_interface_property asic_nreset maxChannel 0
set_interface_property asic_nreset readyLatency 0
set_interface_property asic_nreset ENABLED true
set_interface_property asic_nreset EXPORT_OF ""
set_interface_property asic_nreset PORT_NAME_MAP ""
set_interface_property asic_nreset CMSIS_SVD_VARIABLES ""
set_interface_property asic_nreset SVD_ADDRESS_GROUP ""

add_interface_port asic_nreset ASIC_nReset data Output 1


# 
# connection point asic_enable_f
# 
add_interface asic_enable_f avalon_streaming start
set_interface_property asic_enable_f associatedClock clock
set_interface_property asic_enable_f associatedReset reset
set_interface_property asic_enable_f dataBitsPerSymbol 1
set_interface_property asic_enable_f errorDescriptor ""
set_interface_property asic_enable_f firstSymbolInHighOrderBits true
set_interface_property asic_enable_f maxChannel 0
set_interface_property asic_enable_f readyLatency 0
set_interface_property asic_enable_f ENABLED true
set_interface_property asic_enable_f EXPORT_OF ""
set_interface_property asic_enable_f PORT_NAME_MAP ""
set_interface_property asic_enable_f CMSIS_SVD_VARIABLES ""
set_interface_property asic_enable_f SVD_ADDRESS_GROUP ""

add_interface_port asic_enable_f ASIC_Enable_f data Output 1


# 
# connection point asic_go
# 
add_interface asic_go avalon_streaming start
set_interface_property asic_go associatedClock clock
set_interface_property asic_go associatedReset reset
set_interface_property asic_go dataBitsPerSymbol 1
set_interface_property asic_go errorDescriptor ""
set_interface_property asic_go firstSymbolInHighOrderBits true
set_interface_property asic_go maxChannel 0
set_interface_property asic_go readyLatency 0
set_interface_property asic_go ENABLED true
set_interface_property asic_go EXPORT_OF ""
set_interface_property asic_go PORT_NAME_MAP ""
set_interface_property asic_go CMSIS_SVD_VARIABLES ""
set_interface_property asic_go SVD_ADDRESS_GROUP ""

add_interface_port asic_go ASIC_Go data Output 1


# 
# connection point asic_in
# 
add_interface asic_in avalon_streaming start
set_interface_property asic_in associatedClock clock
set_interface_property asic_in associatedReset reset
set_interface_property asic_in dataBitsPerSymbol 1
set_interface_property asic_in errorDescriptor ""
set_interface_property asic_in firstSymbolInHighOrderBits true
set_interface_property asic_in maxChannel 0
set_interface_property asic_in readyLatency 0
set_interface_property asic_in ENABLED true
set_interface_property asic_in EXPORT_OF ""
set_interface_property asic_in PORT_NAME_MAP ""
set_interface_property asic_in CMSIS_SVD_VARIABLES ""
set_interface_property asic_in SVD_ADDRESS_GROUP ""

add_interface_port asic_in ASIC_In data Output 7


# 
# connection point asic_sel_f
# 
add_interface asic_sel_f avalon_streaming start
set_interface_property asic_sel_f associatedClock clock
set_interface_property asic_sel_f associatedReset reset
set_interface_property asic_sel_f dataBitsPerSymbol 1
set_interface_property asic_sel_f errorDescriptor ""
set_interface_property asic_sel_f firstSymbolInHighOrderBits true
set_interface_property asic_sel_f maxChannel 0
set_interface_property asic_sel_f readyLatency 0
set_interface_property asic_sel_f ENABLED true
set_interface_property asic_sel_f EXPORT_OF ""
set_interface_property asic_sel_f PORT_NAME_MAP ""
set_interface_property asic_sel_f CMSIS_SVD_VARIABLES ""
set_interface_property asic_sel_f SVD_ADDRESS_GROUP ""

add_interface_port asic_sel_f ASIC_Sel_f data Output 1


# 
# connection point asic_mode
# 
add_interface asic_mode avalon_streaming start
set_interface_property asic_mode associatedClock clock
set_interface_property asic_mode associatedReset reset
set_interface_property asic_mode dataBitsPerSymbol 1
set_interface_property asic_mode errorDescriptor ""
set_interface_property asic_mode firstSymbolInHighOrderBits true
set_interface_property asic_mode maxChannel 0
set_interface_property asic_mode readyLatency 0
set_interface_property asic_mode ENABLED true
set_interface_property asic_mode EXPORT_OF ""
set_interface_property asic_mode PORT_NAME_MAP ""
set_interface_property asic_mode CMSIS_SVD_VARIABLES ""
set_interface_property asic_mode SVD_ADDRESS_GROUP ""

add_interface_port asic_mode ASIC_Mode data Output 1


# 
# connection point asic_s1
# 
add_interface asic_s1 avalon_streaming start
set_interface_property asic_s1 associatedClock clock
set_interface_property asic_s1 associatedReset reset
set_interface_property asic_s1 dataBitsPerSymbol 1
set_interface_property asic_s1 errorDescriptor ""
set_interface_property asic_s1 firstSymbolInHighOrderBits true
set_interface_property asic_s1 maxChannel 0
set_interface_property asic_s1 readyLatency 0
set_interface_property asic_s1 ENABLED true
set_interface_property asic_s1 EXPORT_OF ""
set_interface_property asic_s1 PORT_NAME_MAP ""
set_interface_property asic_s1 CMSIS_SVD_VARIABLES ""
set_interface_property asic_s1 SVD_ADDRESS_GROUP ""

add_interface_port asic_s1 ASIC_S1 data Output 1


# 
# connection point asic_s2
# 
add_interface asic_s2 avalon_streaming start
set_interface_property asic_s2 associatedClock clock
set_interface_property asic_s2 associatedReset reset
set_interface_property asic_s2 dataBitsPerSymbol 1
set_interface_property asic_s2 errorDescriptor ""
set_interface_property asic_s2 firstSymbolInHighOrderBits true
set_interface_property asic_s2 maxChannel 0
set_interface_property asic_s2 readyLatency 0
set_interface_property asic_s2 ENABLED true
set_interface_property asic_s2 EXPORT_OF ""
set_interface_property asic_s2 PORT_NAME_MAP ""
set_interface_property asic_s2 CMSIS_SVD_VARIABLES ""
set_interface_property asic_s2 SVD_ADDRESS_GROUP ""

add_interface_port asic_s2 ASIC_S2 data Output 1


# 
# connection point asic_s3
# 
add_interface asic_s3 avalon_streaming start
set_interface_property asic_s3 associatedClock clock
set_interface_property asic_s3 associatedReset reset
set_interface_property asic_s3 dataBitsPerSymbol 1
set_interface_property asic_s3 errorDescriptor ""
set_interface_property asic_s3 firstSymbolInHighOrderBits true
set_interface_property asic_s3 maxChannel 0
set_interface_property asic_s3 readyLatency 0
set_interface_property asic_s3 ENABLED true
set_interface_property asic_s3 EXPORT_OF ""
set_interface_property asic_s3 PORT_NAME_MAP ""
set_interface_property asic_s3 CMSIS_SVD_VARIABLES ""
set_interface_property asic_s3 SVD_ADDRESS_GROUP ""

add_interface_port asic_s3 ASIC_S3 data Output 1

